set(headers ${headers}
	src/PCH.h
	src/clean_cosaves.h
	src/fixes/animation_load_signed_crash.h
	src/fixes/archery_downward_aiming.h
	src/fixes/bethesda_net_crash.h
	src/fixes/bgskeywordform_load_crash.h
	src/fixes/bslightingambientspecular.h
	src/fixes/bslightingshader_force_alpha_test.h
	src/fixes/bslightingshader_parallax_bug.h
	src/fixes/bslightingshaderproperty_shadowmap.h
	src/fixes/bstempeffect_nirtti.h
	src/fixes/calendar_skipping.h
	src/fixes/cell_init.h
	src/fixes/climate_load.h
	src/fixes/conjuration_enchant_absorbs.h
	src/fixes/create_armor_node_nullptr_crash.h
	src/fixes/double_perk_apply.h
	src/fixes/equip_shout_event_spam.h
	src/fixes/esl_cell_loading_bug.h
	src/fixes/facegen_morphdatahead_nullptr_crash.h
	src/fixes/fixes.h
	src/fixes/get_keyword_item_count.h
	src/fixes/gheap_leak_detection_crash.h
	src/fixes/global_time.h
	src/fixes/initialize_hit_data_nullptr_crash.h
	src/fixes/lip_sync.h
	src/fixes/memory_access_errors.h
	src/fixes/mo5s_typo.h
	src/fixes/music_overlap.h
	src/fixes/null_process_crash.h
	src/fixes/perk_fragment_is_running.h
	src/fixes/precomputed_paths.h
	src/fixes/removed_spellbook.h
	src/fixes/save_screenshots.h
	src/fixes/saved_havok_data_load_init.h
	src/fixes/shadowscenenode_nullptr_crash.h
	src/fixes/texture_load_crash.h
	src/fixes/torch_landscape.h
	src/fixes/tree_reflections.h
	src/fixes/vertical_look_sensitivity.h
	src/fixes/weapon_block_scaling.h
	src/memory/allocator.h
	src/memory/havok_memory_system.h
	src/memory/memory.h
	src/memory/memory_manager.h
	src/memory/renderpass_cache.h
	src/memory/scaleform_allocator.h
	src/memory/scrapheap.h
	src/patches/disable_chargen_precache.h
	src/patches/disable_snow_flag.h
	src/patches/enable_achievements.h
	src/patches/form_caching.h
	src/patches/ini_setting_collection.h
	src/patches/max_stdio.h
	src/patches/patches.h
	src/patches/regular_quicksaves.h
	src/patches/safe_exit.h
	src/patches/save_added_sound_categories.h
	src/patches/save_game_max_size.h
	src/patches/scrolling_doesnt_switch_pov.h
	src/patches/sleep_wait_time.h
	src/patches/tree_lod_reference_caching.h
	src/patches/waterflow_animation.h
	src/settings.h
	src/warnings/warnings.h
)
