set(sources ${sources}
	src/fixes.cpp
	src/main.cpp
	src/patches.cpp
	src/PCH.cpp
	src/utils.cpp
	src/warnings.cpp
	src/fixes/doubleperkapply.cpp
	src/fixes/globaltime.cpp
	src/fixes/miscfixes.cpp
	src/fixes/savescreenshots.cpp
	src/fixes/shaderfixes.cpp
	src/patches/formcaching.cpp
	src/patches/memorymanager.cpp
	src/patches/miscpatches.cpp
	src/patches/safeexit.cpp
	src/patches/saveaddedsoundcategories.cpp
	src/patches/scaleformallocator.cpp
	src/patches/treelodreferencecaching.cpp
	src/warnings/miscwarnings.cpp
)
